import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Open Attestation Verification App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/bee.svg" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="/">EPN Certification Verification</a>
        </h1>

        <p className={styles.description}>
          Technology demonstration based on Next.js and <a target="_blank" href="https://github.com/Open-Attestation">https://github.com/Open-Attestation</a>
        </p>

        <div className={styles.grid}>


          <div
            className={styles.card}
          >
            <h2>EPN Certification Verify &rarr;</h2>
            <p>
              Please upload your EPN Certification
              <p>&nbsp;</p>
              <form method="post" action="/api/verification" enctype="multipart/form-data">
                <input type="file" name="cert" id="file-input" className={styles.fileinputbutton} />
                <p>&nbsp;</p>
                <button type="submit" className={styles.button}>
                  Verify Certification
                </button>
              </form>

            </p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        Copyright	&copy; 2024 by MetaLogIQ
      </footer>
    </div>
  )
}
